### ISSUE TITLE
Exclude multiple folders not working

### ISSUE THREAD

**Issue by WillGunn** [Squidly271/ca.backup2#2]
https://github.com/Squidly271/ca.backup2/blob/797f13fe851fcd26130a4b2459e056787d547a2b/source/ca.backup2/usr/local/emhttp/plugins/ca.backup2/scripts/backup.php#L169-L171

Based on this, I think you're accidentally referencing the list of folders instead of each exclusion in the foreach loop, this line should be 
`$rsyncExcluded .= '--exclude "'.rtrim($exclusions,"/").'" ';`

**Comment by Squidly271** [comment]
Exclusions is an array not a string.
